// <auto-generated />
using Codecool.CodecoolShop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Codecool.CodecoolShop.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Codecool.CodecoolShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "EUR",
                            DefaultPrice = 1849m,
                            Description = "The Canon RF 15-35mm f/2.8 is a full-frame pro wide-angle zoom lens offering superior performance thanks to a Nano USM motor, 5-stops of image stabilisation plus 3 Aspherical and 2 UD elements for stunning sharpness.",
                            Name = "Canon RF 15-35mm f2.8 L IS USM",
                            ProductCategoryId = 1,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Currency = "EUR",
                            DefaultPrice = 2349m,
                            Description = "The Canon RF 85mm F1.2L USM is designed for Canon R series mirrorless cameras and is the perfect full frame lens for portraits. With a fast f/1.2 aperture, this lens is superb in low light and is also great for \"bokeh\" as it includes 9 aperture blades.",
                            Name = "Canon RF 85mm f1.2 L IS USM",
                            ProductCategoryId = 1,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Currency = "EUR",
                            DefaultPrice = 379m,
                            Description = "The Canon RF 16mm f/2.8 STM is a compact wide-angle prime with a bright maximum aperture ideal for photographing architectural subjects and astrophotography scenes.",
                            Name = "Canon RF 16mm f2.8 STM",
                            ProductCategoryId = 1,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            Currency = "EUR",
                            DefaultPrice = 6039m,
                            Description = "The EOS R3 Mirrorless Digital Camera is a fast-shooting all-in-one camera from Canon that equipped with new full-frame imaging technologies and improved AF performance for advanced amateurs and professionals.",
                            Name = "Canon EOS R3",
                            ProductCategoryId = 2,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 5,
                            Currency = "EUR",
                            DefaultPrice = 2139m,
                            Description = "The Canon EOS R6 is a versatile full-frame, weather-resistant mirrorless camera that's packed with advanced features for both photographers and videographers with 4K 60p video recording.",
                            Name = "Canon EOS R6",
                            ProductCategoryId = 2,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 6,
                            Currency = "EUR",
                            DefaultPrice = 899m,
                            Description = "Impressively small despite having a large full-frame sensor, the Canon EOS RP offers flexible imaging capabilities along with a portable form factor.",
                            Name = "Canon EOS RP",
                            ProductCategoryId = 2,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 7,
                            Currency = "EUR",
                            DefaultPrice = 719m,
                            Description = "The Nikon Z 24mm f/1.8 S is a wide prime lens for Nikon’s FX-format Z-series mirrorless cameras. This prime lens is ideal for architecture & landscape photography and with extensive weather sealing, you can use this lens in all conditions.",
                            Name = "Nikon NIKKOR Z 24mm f1.8 S",
                            ProductCategoryId = 1,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 8,
                            Currency = "EUR",
                            DefaultPrice = 1889m,
                            Description = "Bright and versatile, the NIKKOR Z 24-70mm f/2.8 S from Nikon is a workhorse standard zoom, covering wide-angle to portrait-length fields of view.",
                            Name = "Nikon NIKKOR Z 24-70mm f2.8 S",
                            ProductCategoryId = 1,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 9,
                            Currency = "EUR",
                            DefaultPrice = 1719m,
                            Description = "The NIKKOR Z 14-24mm f/2.8 S is an advanced optical designed ultra-wide-angle zoom lens. The large f/2.8 constant maximum aperture suits working in low-light conditions when shooting handheld and also offers improved depth of field control.",
                            Name = "Nikon NIKKOR Z 14-24mm f2.8 S",
                            ProductCategoryId = 1,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 10,
                            Currency = "EUR",
                            DefaultPrice = 6499m,
                            Description = "The Nikon Z9 flagship full-frame mirrorless camera is ideal for detail-oriented stills shooting as well as high resolution videos recording for professionals and shutterbugs.",
                            Name = "Nikon Z9",
                            ProductCategoryId = 2,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 11,
                            Currency = "EUR",
                            DefaultPrice = 2599m,
                            Description = "The Nikon Z7 II is a lightweight, full-frame mirrorless camera with a high-resolution 45.7MP BSI CMOS sensor and dual EXPEED 6 image processors which offers superb speed and fast processing.",
                            Name = "Nikon Z7 II",
                            ProductCategoryId = 2,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 12,
                            Currency = "EUR",
                            DefaultPrice = 1059m,
                            Description = "The latest in Nikon's Z series, the Nikon Z 5 is a tough, lightweight, weather-sealed & easy-to-use full-frame camera that is truly portable and is great for both still photography as well as 4K video shooting.",
                            Name = "Nikon Z5",
                            ProductCategoryId = 2,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 13,
                            Currency = "EUR",
                            DefaultPrice = 1339m,
                            Description = "A dynamic ultra wide-angle focal length with an especially bright design, the FE 14mm f/1.8 GM from Sony is a fast, versatile lens well-suited to landscape, nature, architectural, and astrophotography applications.",
                            Name = "Sony FE 14mm f1.8 GM",
                            ProductCategoryId = 1,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 14,
                            Currency = "EUR",
                            DefaultPrice = 2699m,
                            Description = "The FE 70-200mm f/2.8 GM OSS II Lens is the latest large-aperture telephoto zoom G Master Lens from Sony upgraded from the previous model. With an advanced optical design, the unit affords phenomenal high resolution, along with smooth background defocus effects.",
                            Name = "Sony FE 70-200mm f2.8 GM OSS II",
                            ProductCategoryId = 1,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 15,
                            Currency = "EUR",
                            DefaultPrice = 2359m,
                            Description = "Comprising a range of ultra-wide fields of view, the Sony FE 12-24mm f/2.8 GM is a bright and versatile zoom characterized by its broad range and bright design.",
                            Name = "Sony FE 12-24mm f2.8 GM",
                            ProductCategoryId = 1,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 16,
                            Currency = "EUR",
                            DefaultPrice = 5749m,
                            Description = "The Alpha 1 Mirrorless Digital Camera is a phenomenal all-in-one flagship full frame camera from Sony offers exceptionally high resolution still images and amazing 8K videos in a sophisticated designed compact body.",
                            Name = "Sony α a1",
                            ProductCategoryId = 2,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 17,
                            Currency = "EUR",
                            DefaultPrice = 2499m,
                            Description = "This novel Alpha a7R IV (ILCE-7RM4A) Mirrorless Digital Camera from Sony is an upgrade version from the fourth edition of the a7R series and includes a high 2.35m-dot resolution 3-inch rear tilting touchscreen LCD and a SuperSpeed USB 5Gbps (USB 3.2) USB port with a 61MP Exmor R BSI CMOS sensor and enhanced BIONZ X image processor.",
                            Name = "Sony α a7R IV",
                            ProductCategoryId = 2,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 18,
                            Currency = "EUR",
                            DefaultPrice = 1699m,
                            Description = "The new Sony a7C body in black gives you full-frame pro-quality in a stylish, compact and lightweight design that is super portable. Features include a backside illuminated full-frame CMOS 24.2MP sensor, 4K movie recording, in-body 5-axis image stabilisation, fast real-time autofocus, ISO 100-51200 for great image quality, even in low-light conditions, 3-inch vari-angle touchscreen.",
                            Name = "Sony α a7C",
                            ProductCategoryId = 2,
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("Codecool.CodecoolShop.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Camera Lens",
                            Description = "Quality lenses from the top Camera manufacturers.",
                            Name = "Lens"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Camera Body",
                            Description = "Top of the line Mirrorless digital camera bodies.",
                            Name = "Body"
                        });
                });

            modelBuilder.Entity("Codecool.CodecoolShop.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Canon Inc. (キヤノンキャノン株式会社) is a Japanese multinational corporation headquartered in Ōta, Tokyo, Japan, specializing in optical, imaging, and industrial products, such as lenses, cameras, medical equipment, scanners, printers, and semiconductor manufacturing equipment.",
                            Name = "Canon"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nikon Corporation (株式会社ニコン), also known just as Nikon, is a Japanese multinational corporation headquartered in Tokyo, Japan, specializing in optics and imaging products. The companies held by Nikon form the Nikon Group.",
                            Name = "Nikon"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sony Group Corporation (ソニーグループ株式会社), commonly known as Sony and stylized as SONY, is a Japanese multinational conglomerate corporation headquartered in Kōnan, Minato, Tokyo, Japan.",
                            Name = "Sony"
                        });
                });

            modelBuilder.Entity("Codecool.CodecoolShop.Models.Product", b =>
                {
                    b.HasOne("Codecool.CodecoolShop.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codecool.CodecoolShop.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Codecool.CodecoolShop.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Codecool.CodecoolShop.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
